services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: ""
    startCommand: |
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn django_porfolio.wsgi:application
